# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_images',
            new_name='profile_image',
        ),
    ]
