# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_tages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tages',
            new_name='tags',
        ),
    ]
